import type React from "react";

/** Shared inline styles for the auth screens (no CSS framework; on-brand purple). */
export const s: Record<string, React.CSSProperties> = {
  page: {
    position: "fixed",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    background:
      "radial-gradient(1200px 600px at 50% -10%, #ece9ff 0%, #f7f7fb 45%, #f3f4f6 100%)",
    fontFamily:
      "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
    color: "#1b1b1f",
    zIndex: 2000,
  },
  card: {
    width: "min(420px, 100%)",
    background: "#fff",
    borderRadius: 14,
    padding: "32px 28px",
    boxShadow: "0 18px 50px rgba(28,25,90,0.14)",
    border: "1px solid #ecebf3",
  },
  brand: {
    fontSize: 22,
    fontWeight: 700,
    letterSpacing: "-0.02em",
    marginBottom: 4,
  },
  sub: { fontSize: 14, color: "#6b7280", marginBottom: 24 },
  tabs: {
    display: "flex",
    gap: 4,
    background: "#f3f4f6",
    borderRadius: 10,
    padding: 4,
    marginBottom: 22,
  },
  tab: {
    flex: 1,
    textAlign: "center",
    padding: "8px 0",
    borderRadius: 7,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    border: "none",
    background: "transparent",
    color: "#6b7280",
  },
  tabActive: {
    background: "#fff",
    color: "#1b1b1f",
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
  },
  label: {
    display: "block",
    fontSize: 13,
    fontWeight: 600,
    marginBottom: 6,
    marginTop: 14,
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    padding: "11px 12px",
    borderRadius: 9,
    border: "1px solid #d7d7e0",
    fontSize: 15,
    outline: "none",
    background: "#fff",
  },
  primary: {
    width: "100%",
    marginTop: 22,
    padding: "12px 0",
    borderRadius: 10,
    border: "none",
    background: "#6965db",
    color: "#fff",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
  },
  ghost: {
    width: "100%",
    marginTop: 10,
    padding: "11px 0",
    borderRadius: 10,
    border: "1px solid #d7d7e0",
    background: "#fff",
    color: "#1b1b1f",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  linkRow: {
    marginTop: 16,
    textAlign: "center",
    fontSize: 13,
    color: "#6b7280",
  },
  link: {
    color: "#6965db",
    cursor: "pointer",
    fontWeight: 600,
    background: "none",
    border: "none",
    padding: 0,
  },
  error: {
    marginTop: 16,
    padding: "10px 12px",
    borderRadius: 8,
    background: "#fdecec",
    color: "#b42318",
    fontSize: 13,
  },
  notice: {
    marginTop: 16,
    padding: "10px 12px",
    borderRadius: 8,
    background: "#eafaf0",
    color: "#067647",
    fontSize: 13,
  },
  divider: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    margin: "20px 0 4px",
    color: "#9ca3af",
    fontSize: 12,
  },
  hr: { flex: 1, height: 1, background: "#ececf3", border: "none" },
};
